# -*- coding: utf-8 -*-
"""utils_query_handler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-sET1E6hYAkbd7meR9quekOyZQS80NA
"""

def retrieve_user_context(collection, model, query):
    query_embedding = model.encode(query).tolist()
    results = collection.query(query_embeddings=[query_embedding], n_results=1)

    if results["documents"]:
        return results["documents"][0][0], results["metadatas"][0][0]
    return None, None